"""initial

Revision ID: 7b27956007a6
Revises: 
Create Date: 2025-02-27 18:20:11.715233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b27956007a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_tools', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tools', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tool_choice', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enable_thinking', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('thinking_budget_tokens', sa.Integer(), server_default='16000', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('thinking_budget_tokens')
        batch_op.drop_column('enable_thinking')
        batch_op.drop_column('tool_choice')
        batch_op.drop_column('tools')
        batch_op.drop_column('enable_tools')

    # ### end Alembic commands ### 